[workspace]
members = ["ncollide2d-cpp", "ncollide3d-cpp"]

[patch.crates-io]
ncollide2d = { path = "external/ncollide.git/build/ncollide2d" }
ncollide3d = { path = "external/ncollide.git/build/ncollide3d" }
